pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - check-success=Build Pull Requests
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
